books/urls.py
from django.urls import path
from books import views as book_views

app_name = "books"

urlpatterns = [
    path("", book_views.BookListView.as_view(), name="book-list"),
    path("<int:pk>/", book_views.BookDetailView.as_view(), name="book-detail"),
    path("create/", book_views.CreateBookmView.as_view(), name="book-create"),
    path("<int:pk>/edit/", book_views.EditBookView.as_view(), name="book-edit"),
]

config/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("books/", include("books.urls", namespace="books")),
    path("movies/", include("movies.urls", namespace="movies")),
    path("category/", include("categories.urls", namespace="category")),
    path("people/", include("people.urls", namespace="people")),
    path("users/", include("users.urls", namespace="users")),
    path("favs/", include("favs.urls", namespace="favs")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from core import views as core_views

app_name = "core"

urlpatterns = [
    path("", core_views.homeView, name="home"),
    path("search/", core_views.searchView, name="search"),
]

favs/urls.py
from django.urls import path
from favs import views as fav_views

app_name = "favs"

urlpatterns = [
    path("list/", fav_views.fav_list, name="favs-list"),
    path("add/<int:pk>/", fav_views.toggleList, name="add-favs"),
]

movies/urls.py
from django.urls import path
from movies import views as movie_views

app_name = "movies"

urlpatterns = [
    path("", movie_views.MovieListView.as_view(), name="movie-list"),
    path("<int:pk>/", movie_views.MovieDetailView.as_view(), name="movie-detail"),
    path("create/", movie_views.CreateMovieView.as_view(), name="movie-create"),
    path("<int:pk>/edit/", movie_views.EditMovieView.as_view(), name="movie-edit"),
]

people/urls.py
from django.urls import path
from people import views as person_views

app_name = "people"

urlpatterns = [
    path(
        "",
        person_views.PersonListView.as_view(),
        name="person-list",
    ),
    path(
        "<int:pk>/",
        person_views.PeopleDetailView.as_view(),
        name="person-detail",
    ),
    path(
        "create/",
        person_views.CreatePersonView.as_view(),
        name="person-create",
    ),
    path(
        "<int:pk>/edit/",
        person_views.EditPersonView.as_view(),
        name="person-edit",
    ),
]

reviews/urls.py
from django.urls import path
from reviews import views as review_views

app_name = "reviews"

urlpatterns = [
    path("create/", review_views.CreateReviewView.as_view(), name="create-review"),
    path("delete/", review_views.deleteReview, name="delete-review"),
]

books/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db.models import Q
from django.shortcuts import reverse

from core import models as core_models


class Book(core_models.TimeStampedModel):

    """Book Model Definition"""

    title = models.CharField(max_length=100)
    year = models.IntegerField(validators=[MinValueValidator(0)])
    cover_image = models.ImageField(upload_to="book_cover_images", blank=True)
    rating = models.FloatField(validators=[MinValueValidator(0), MaxValueValidator(5)])
    category = models.ForeignKey(
        "categories.Category",
        related_name="books",
        on_delete=models.CASCADE,
        null=True,
        limit_choices_to=Q(kind="both") | Q(kind="book"),
    )
    writer = models.ForeignKey(
        "people.Person",
        related_name="books",
        on_delete=models.CASCADE,
        limit_choices_to={"kind": "writer"},
    )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("books:book-detail", kwargs={"pk": self.pk})

people/models.py
from django.db import models
from django.shortcuts import reverse

from core import models as core_models


class Person(core_models.TimeStampedModel):

    """Person Model Definition"""

    KIND_ACTOR = "actor"
    KIND_DIRECTOR = "director"
    KIND_WRITER = "writer"

    KIND_CHOICES = (
        (KIND_ACTOR, "Actor"),
        (KIND_DIRECTOR, "Director"),
        (KIND_WRITER, "Writer"),
    )

    name = models.CharField(max_length=100)
    kind = models.CharField(max_length=20, choices=KIND_CHOICES)
    photo = models.ImageField(upload_to="people_images", blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("people:person-detail", kwargs={"pk": self.pk})

    class Meta:
        verbose_name_plural = "People"

books/forms.py
from django import forms
from books.models import Book


class CreateBookForm(forms.ModelForm):

    """Create Book Form Definition"""

    class Meta:
        model = Book
        fields = (
            "title",
            "year",
            "rating",
            "category",
            "writer",
            "cover_image",
        )

    def save(self, *args, **kwargs):
        book = super().save(commit=False)
        return book

people/forms.py
from django import forms
from people.models import Person


class CreatePersonForm(forms.ModelForm):

    """Create Person Form Definition"""

    class Meta:
        model = Person
        fields = (
            "name",
            "kind",
            "photo",
        )

    def save(self, *args, **kwargs):
        Movie = super().save(commit=False)
        return Movie

books/views.py
from django.views.generic import ListView, DetailView, FormView, UpdateView
from django.shortcuts import redirect, reverse

from books.models import Book
from reviews.models import Review
from books.forms import CreateBookForm


class BookListView(ListView):

    """Book List View"""

    model = Book
    template_name = "pages/books/book_list.html"
    context_object_name = "books"
    paginate_by = 10
    paginate_orphans = 5
    ordering = ["-year"]

    def get_context_data(self):
        page = int(self.request.GET.get("page", 1))
        page_sector = (page - 1) // 5
        page_sector = page_sector * 5
        context = super().get_context_data()
        context["page_sector"] = page_sector
        return context


class BookDetailView(DetailView):

    """Book Detail View"""

    model = Book
    template_name = "pages/books/book_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        book = context["book"]
        reviews = Review.objects.filter(book=book)
        context["reviews"] = reviews
        return context


class CreateBookmView(FormView):

    """Create Book View Definition"""

    form_class = CreateBookForm
    template_name = "pages/books/create_book.html"

    def form_valid(self, form):
        book = form.save()
        book.save()
        return redirect(reverse("books:book-detail", kwargs={"pk": book.pk}))


class EditBookView(UpdateView):

    """Edit Book View Definition"""

    model = Book
    template_name = "pages/books/edit_book.html"
    fields = (
        "title",
        "year",
        "rating",
        "category",
        "writer",
    )

    def get_form(self, form_class=None):
        form = super().get_form(form_class=form_class)
        form.fields["title"].widget.attrs = {"class": "w-full", "placeholder": "Title"}
        form.fields["year"].widget.attrs = {"class": "w-full", "placeholder": "Year"}
        form.fields["rating"].widget.attrs = {
            "class": "w-full",
            "placeholder": "Rating",
        }
        return form

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        return context

people/views.py
from django.views.generic import ListView, DetailView, FormView, UpdateView
from django.shortcuts import redirect, reverse

from people.models import Person
from people.forms import CreatePersonForm


class PersonListView(ListView):

    """Person List View"""

    model = Person
    template_name = "pages/people/person_list.html"
    context_object_name = "people"
    paginate_by = 12
    paginate_orphans = 6
    ordering = "created"

    def get_context_data(self):
        page = int(self.request.GET.get("page", 1))
        page_sector = (page - 1) // 5
        page_sector = page_sector * 5
        context = super().get_context_data()
        context["page_sector"] = page_sector
        return context


class PeopleDetailView(DetailView):

    """People Detail View"""

    model = Person
    template_name = "pages/people/person_detail.html"


class CreatePersonView(FormView):

    """Create Person View Definition"""

    form_class = CreatePersonForm
    template_name = "pages/people/create_person.html"

    def form_valid(self, form):
        person = form.save()
        person.save()
        return redirect(reverse("people:person-detail", kwargs={"pk": person.pk}))


class EditPersonView(UpdateView):

    """Edit Person View Definition"""

    model = Person
    template_name = "pages/people/edit_person.html"
    fields = (
        "name",
        "kind",
        "photo",
    )

    def get_form(self, form_class=None):
        form = super().get_form(form_class=form_class)
        form.fields["name"].widget.attrs = {"class": "w-full", "placeholder": "Title"}
        return form

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        return context

templates/mixins/book.html
{% load on_favs %}

<div class="relative group show_up_book opacity-0">
  <a href="{% url 'books:book-detail' book.pk %}">
    <img class="cover_image" src="{{book.cover_image.url|default_if_none:" "}}" alt="Cover Image">
  </a>
  <div class="font-bold text-gray-600 group-hover:opacity-100 absolute bottom-20 right-3 opacity-0">
    {{book.rating}}
    / 5.0
  </div>
  <div class="font-bold">
    {{book.title|truncatechars:27}}
  </div>
  <div>
    {{book.year}}
  </div>
  {% is_book_on_favs book as on_favs_boolean %}
  {% if on_favs_boolean %}
    <a href="{% url 'favs:add-favs' book.pk %}?type=book" class="mr-3 absolute top-5 right-2">
      <i class="fas text-red-500 fa-heart  text-2xl justify-end text-center"></i>
    </a>
  {% else %}
    <a href="{% url 'favs:add-favs' book.pk %}?type=book" class="mr-3 absolute top-5 right-2">
      <i class="far fa-heart  text-2xl text-white justify-end text-center"></i>
    </a>
  {% endif %}
</div>

templates/mixins/movie.html
{% load on_favs %}

<div class="relative group show_up_movie opacity-0">
  <a href="{% url 'movies:movie-detail' movie.pk %}">
    <img class="cover_image" src="{{movie.cover_image.url|default_if_none:" "}}" alt="Cover Image">
  </a>
  <div class="font-bold text-gray-600 group-hover:opacity-100 absolute bottom-20 right-3 opacity-0">
    {{movie.rating}}
    / 5.0
  </div>
  <div class="font-bold">
    {{movie.title|truncatechars:27}}
  </div>
  <div>
    {{movie.year}}
  </div>
  {% is_movie_on_favs movie as on_favs_boolean %}
  {% if on_favs_boolean %}
    <a href="{% url 'favs:add-favs' movie.pk %}?type=movie" class="mr-3 absolute top-5 right-2">
      <i class="fas text-red-500 fa-heart  text-2xl justify-end text-center"></i>
    </a>
  {% else %}
    <a href="{% url 'favs:add-favs' movie.pk %}?type=movie" class="mr-3 absolute top-5 right-2">
      <i class="far fa-heart  text-2xl text-white justify-end text-center"></i>
    </a>
  {% endif %}
</div>

templates/mixins/page_number.html
{% comment %}  {% endcomment %}
<div class="flex justify-center mb-20">
  {% if page_obj.has_previous %}
    {% if page_sector|add:-4 <= 1 %}
      <a href="?page=1" class="mr-3 text-lg font-semibold">Prev</a>
    {% else %}
      <a href="?page={{page_sector|add:-4}}" class="mr-3 text-lg font-semibold">Prev</a>
    {% endif %}
  {% endif %}
  {% for number in '12345'|make_list %}
    {% if page_sector|add:number <= page_obj.paginator.num_pages %}
      <a href="?page={{page_sector|add:number}}" class="mr-2 py-1 px-2 text-lg rounded {% if page_sector|add:number == page_obj.number %} bg-green-400 text-white {% else %}text-gray-700 bg-gray-200{% endif %} hover:bg-green-200 hover:text-white">{{page_sector|add:number}}</a>
    {% endif %}
  {% endfor %}
  {% if page_obj.has_next %}
    {% if page_sector|add:6 >= page_obj.paginator.num_pages %}
      <a href="?page={{page_obj.paginator.num_pages}}" class="ml-1 text-lg font-semibold">Next</a>
    {% else %}
      <a href="?page={{page_sector|add:6}}" class="ml-1 text-lg font-semibold">Next</a>
    {% endif %}
  {% endif %}
</div>

templates/mixins/person.html
<div class="relative group show_up_people opacity-0">
  <a href="{% url 'people:person-detail' person.pk %}">
    <img class="cover_image" src="{{person.photo.url}}" alt="">
  </a>
  <div>
    <div class="font-bold">
      {{person.name|truncatechars:27}}
    </div>
    <div>
      {{person.kind|capfirst}}
    </div>
  </div>
</div>

templates/mixins/reviews.html
<div class="mt-20 mb-40 bg-gray-200 px-10 mx-20 py-10 rounded-lg">
  <div class="flex justify-between mb-5">
    <h2 class="font-bold text-xl">Reviews</h2>
    <button class="bg-gray-500 text-white rounded-lg text-base font-bold tracking-wider outline-none border-none px-4 py-2">
      <a class="" href="{% url 'reviews:create-review' %}?type={{type}}&id={{id}}">Write a review</a>
    </button>
  </div>
  <div class="grid grid-cols-2 gap-x-20 gap-y-10">
    {% for review in reviews.all %}
      <div class="flex flex-col border rounded-lg py-5 px-4 border-gray-300 w-full h-full">
        <div class="flex justify-between">
          <div>
            <div class="flex">
              <span>{{review.created_by}}</span>
              <span class="mx-2">|</span>
              <span>{{review.rating}}</span>
            </div>
            <div class="my-2 text-xs">
              {{review.created}}
            </div>
          </div>
          <button class="mr-10 self-start delete_button">
            <a href="{% url 'reviews:delete-review' %}?type={{type}}&reviewId={{review.pk}}">Delete</a>
          </button>
        </div>
        <br>
        <div class="w-full h-32 break-words overflow-y-scroll">
          {{review.text}}
        </div>
      </div>
    {% endfor %}
  </div>
</div>