books/urls.py
from django.urls import path
from books import views as book_views

app_name = "books"

urlpatterns = [
    path("", book_views.BookListView.as_view(), name="book-list"),
    path("<int:pk>/", book_views.BookDetailView.as_view(), name="book-detail"),
    path("create/", book_views.CreateBookmView.as_view(), name="book-create"),
    path("<int:pk>/edit/", book_views.EditBookView.as_view(), name="book-edit"),
]

config/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("books/", include("books.urls", namespace="books")),
    path("movies/", include("movies.urls", namespace="movies")),
    path("category/", include("categories.urls", namespace="category")),
    path("people/", include("people.urls", namespace="people")),
    path("users/", include("users.urls", namespace="users")),
    path("favs/", include("favs.urls", namespace="favs")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from core import views as core_views

app_name = "core"

urlpatterns = [
    path("", core_views.homeView, name="home"),
    path("search/", core_views.searchView, name="search"),
]

books/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db.models import Q
from django.shortcuts import reverse

from core import models as core_models


class Book(core_models.TimeStampedModel):

    """Book Model Definition"""

    title = models.CharField(max_length=100)
    year = models.IntegerField(validators=[MinValueValidator(0)])
    cover_image = models.ImageField(upload_to="book_cover_images", blank=True)
    rating = models.FloatField(validators=[MinValueValidator(0), MaxValueValidator(5)])
    category = models.ForeignKey(
        "categories.Category",
        related_name="books",
        on_delete=models.CASCADE,
        null=True,
        limit_choices_to=Q(kind="both") | Q(kind="book"),
    )
    writer = models.ForeignKey(
        "people.Person",
        related_name="books",
        on_delete=models.CASCADE,
        limit_choices_to={"kind": "writer"},
    )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("books:book-detail", kwargs={"pk": self.pk})

books/forms.py
from django import forms
from books.models import Book


class CreateBookForm(forms.ModelForm):

    """Create Book Form Definition"""

    class Meta:
        model = Book
        fields = (
            "title",
            "year",
            "rating",
            "category",
            "writer",
            "cover_image",
        )

    def save(self, *args, **kwargs):
        book = super().save(commit=False)
        return book

books/views.py
from django.views.generic import ListView, DetailView, FormView, UpdateView
from django.shortcuts import redirect, reverse

from books.models import Book
from reviews.models import Review
from books.forms import CreateBookForm


class BookListView(ListView):

    """Book List View"""

    model = Book
    template_name = "pages/books/book_list.html"
    context_object_name = "books"
    paginate_by = 10
    paginate_orphans = 5
    ordering = ["-year"]

    def get_context_data(self):
        page = int(self.request.GET.get("page", 1))
        page_sector = (page - 1) // 5
        page_sector = page_sector * 5
        context = super().get_context_data()
        context["page_sector"] = page_sector
        return context


class BookDetailView(DetailView):

    """Book Detail View"""

    model = Book
    template_name = "pages/books/book_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        book = context["book"]
        reviews = Review.objects.filter(book=book)
        context["reviews"] = reviews
        return context


class CreateBookmView(FormView):

    """Create Book View Definition"""

    form_class = CreateBookForm
    template_name = "pages/books/create_book.html"

    def form_valid(self, form):
        book = form.save()
        book.save()
        return redirect(reverse("books:book-detail", kwargs={"pk": book.pk}))


class EditBookView(UpdateView):

    """Edit Book View Definition"""

    model = Book
    template_name = "pages/books/edit_book.html"
    fields = (
        "title",
        "year",
        "rating",
        "category",
        "writer",
    )

    def get_form(self, form_class=None):
        form = super().get_form(form_class=form_class)
        form.fields["title"].widget.attrs = {"class": "w-full", "placeholder": "Title"}
        form.fields["year"].widget.attrs = {"class": "w-full", "placeholder": "Year"}
        form.fields["rating"].widget.attrs = {
            "class": "w-full",
            "placeholder": "Rating",
        }
        return form

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        return context

templates/pages/books/book_detail.html
{% extends 'base.html' %}

{% block page_title %}
  {{book.title}}
{% endblock page_title %}

{% block content %}
  <div class="w-full px-20 mt-20 max-h-full min-h-screen" style="background: rgba(20,20,20,1);">
    <div class="absolute left-1/4 w-1/2 bg-cover bg-no-repeat bg-center h-full opacity-30" style="background-image:url({{book.cover_image.url}})"></div>
    <div class="flex  pt-20 justify-between">
      <div class="flex 3/4">
        <img class="mr-4" src="{{book.cover_image.url}}" alt="Book Cover Image">
        <div class="z-10">
          <div>
            <span class="detail_field">Title :</span>
            <span class="detail_answer">{{book.title}}</span>
          </div>
          <div>
            <span class="detail_answer">{{book.year}}</span>
          </div>
          <div>
            <span class="detail_field">Rating :</span>
            <span class="detail_answer">{{book.rating}}
              / 5.0</span>
          </div>
          <div>
            <span class="detail_field">Category :</span>
            <span class="detail_answer">{{book.category}}</span>
          </div>
          <div>
            <span class="detail_field">Writer :
            </span>
            <span class="detail_answer">{{book.writer}}</span>
          </div>
        </div>
      </div>
      <a class="edit_button" href="{% url 'books:book-edit' book.pk %}">Edit Book</a>
    </div>
  </div>
  {% comment %}  {% endcomment %}
  {% include 'mixins/reviews.html' with reviews=reviews type="book" id=book.pk %}
{% endblock content%}

templates/pages/books/book_list.html
{% extends 'base.html' %}
{% comment %}  {% endcomment %}
{% block page_title %}
  Book List
{% endblock page_title %}

{% block content %}
  <div class="mt-40 flex flex-col items-center justify-items-center min-h-screen">
    <div class="w-10/12">
      <div class="flex flex-col">
        <section class="home_section mt-10 p-8 rounded-lg">
          <div class="flex justify-between items-center mb-8">
            <h4 class="text-2xl font-bold ">Latest Books</h4>
            <a href="{% url 'books:book-create' %}" class="font-bold px-4 py-2 border-none rounded-lg bg-green-500 text-white">Create Book</a>
          </div>
          <div class="section_grid">
            {% for book in books %}
              {% include 'mixins/book.html' with book=book %}
            {% endfor %}
          </div>
          <a href="{% url 'books:book-list' %}" class="listLink ">
            Go to Book List &rarr;
          </a>
        </section>
        
        {% include 'mixins/page_number.html' with page_sector=page_sector page_obj=page_obj%}
      </div>
    </div>
  </div>
{% endblock content%}

templates/pages/books/create_book.html
{% extends 'base.html' %}

{% block page_title %}
  Create Book
{% endblock page_title %}

{% block content %}
  <div class="py-20">
    <div class="background">
      <div class="wrap">
        <h1 class="text-3xl font-bold pb-6 pt-3 text-center">Create Book</h1>
        <form method="post" class="form" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="form_input rounded-tr-lg rounded-tl-lg">
            <input type="text" name="title" placeholder="Title" required="required">
          </div>

          <div class="number_input">
            <input type="number" name="year" class="w-full" min="0" placeholder="Year" required="required">
          </div>

          <div class="number_input">
            <input type="number" name="rating" class="w-full" min="0" max="5" placeholder="Rating" required="required">
          </div>

          <div class="border p-3 border-gray-400 flex justify-between">
            <input type="text" name="caption" class="p-1 w-full" placeholder="Caption">
            <input type="file" name="cover_image" class="p-1 w-full">
          </div>

          <div class="select">
            <label for="category">Category</label>
            <select name="category" id="category" required="required">
              {% for aCategory in form.category %}
                {{aCategory}}
              {% endfor %}
            </select>
          </div>

          <div class="select rounded-br-lg rounded-bl-lg">
            <label for="writer">Writer</label>
            <select name="writer" id="writer" required="required">
              {% for aWriter in form.writer %}
                {{aWriter}}
              {% endfor %}
            </select>
          </div>
          <button class="form_button">Create</button>
        </form>
        <a href="{% url 'books:book-list' %}" class="block text-center w-full mt-3 px-1 py-2 bg-gray-500 text-white rounded-lg text-base font-bold tracking-wider outline-none border-none;">Back</a>
      </div>
    </div>
  </div>
{% endblock content %}

templates/pages/books/edit_book.html
{% extends 'base.html' %}

{% block page_title %}
  Edit Book
{% endblock page_title %}

{% block content %}
  <div class="background">
    <div class="wrap">
      <h1 class="text-3xl font-bold pb-6 pt-3 text-center">Edit Book</h1>
      <form method="post" class="form" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form_input rounded-tr-lg rounded-tl-lg">
          {{form.title}}
        </div>

        <div class="number_input">
          {{form.year}}
        </div>

        <div class="number_input">
          {{form.rating}}
        </div>

        <div class="border p-3 border-gray-400 flex justify-between">
          <input type="text" name="caption" class="p-1 w-full" placeholder="Caption">
          <input type="file" name="cover_image" class="p-1 w-full">
        </div>

        <div class="select">
          <label for="category">Category</label>
          {{form.category}}
        </div>

        <div class="select rounded-br-lg rounded-bl-lg">
          <label for="writer">Writer</label>
          {{form.writer}}
        </div>

        <button class="form_button">Edit</button>
      </form>
    </div>
  </div>
{% endblock content %}