config/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("books/", include("books.urls", namespace="books")),
    path("movies/", include("movies.urls", namespace="movies")),
    path("category/", include("categories.urls", namespace="category")),
    path("people/", include("people.urls", namespace="people")),
    path("users/", include("users.urls", namespace="users")),
    path("favs/", include("favs.urls", namespace="favs")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from core import views as core_views

app_name = "core"

urlpatterns = [
    path("", core_views.homeView, name="home"),
    path("search/", core_views.searchView, name="search"),
]

people/urls.py
from django.urls import path
from people import views as person_views

app_name = "people"

urlpatterns = [
    path(
        "",
        person_views.PersonListView.as_view(),
        name="person-list",
    ),
    path(
        "<int:pk>/",
        person_views.PeopleDetailView.as_view(),
        name="person-detail",
    ),
    path(
        "create/",
        person_views.CreatePersonView.as_view(),
        name="person-create",
    ),
    path(
        "<int:pk>/edit/",
        person_views.EditPersonView.as_view(),
        name="person-edit",
    ),
]

people/models.py
from django.db import models
from django.shortcuts import reverse

from core import models as core_models


class Person(core_models.TimeStampedModel):

    """Person Model Definition"""

    KIND_ACTOR = "actor"
    KIND_DIRECTOR = "director"
    KIND_WRITER = "writer"

    KIND_CHOICES = (
        (KIND_ACTOR, "Actor"),
        (KIND_DIRECTOR, "Director"),
        (KIND_WRITER, "Writer"),
    )

    name = models.CharField(max_length=100)
    kind = models.CharField(max_length=20, choices=KIND_CHOICES)
    photo = models.ImageField(upload_to="people_images", blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("people:person-detail", kwargs={"pk": self.pk})

    class Meta:
        verbose_name_plural = "People"

people/forms.py
from django import forms
from people.models import Person


class CreatePersonForm(forms.ModelForm):

    """Create Person Form Definition"""

    class Meta:
        model = Person
        fields = (
            "name",
            "kind",
            "photo",
        )

    def save(self, *args, **kwargs):
        Movie = super().save(commit=False)
        return Movie

people/views.py
from django.views.generic import ListView, DetailView, FormView, UpdateView
from django.shortcuts import redirect, reverse

from people.models import Person
from people.forms import CreatePersonForm


class PersonListView(ListView):

    """Person List View"""

    model = Person
    template_name = "pages/people/person_list.html"
    context_object_name = "people"
    paginate_by = 12
    paginate_orphans = 6
    ordering = "created"

    def get_context_data(self):
        page = int(self.request.GET.get("page", 1))
        page_sector = (page - 1) // 5
        page_sector = page_sector * 5
        context = super().get_context_data()
        context["page_sector"] = page_sector
        return context


class PeopleDetailView(DetailView):

    """People Detail View"""

    model = Person
    template_name = "pages/people/person_detail.html"


class CreatePersonView(FormView):

    """Create Person View Definition"""

    form_class = CreatePersonForm
    template_name = "pages/people/create_person.html"

    def form_valid(self, form):
        person = form.save()
        person.save()
        return redirect(reverse("people:person-detail", kwargs={"pk": person.pk}))


class EditPersonView(UpdateView):

    """Edit Person View Definition"""

    model = Person
    template_name = "pages/people/edit_person.html"
    fields = (
        "name",
        "kind",
        "photo",
    )

    def get_form(self, form_class=None):
        form = super().get_form(form_class=form_class)
        form.fields["name"].widget.attrs = {"class": "w-full", "placeholder": "Title"}
        return form

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        return context

templates/pages/people/create_person.html
{% extends 'base.html' %}

{% block page_title %}
  Create Person
{% endblock page_title %}

{% block content %}
  <div class="py-20">
    <div class="background">
      <div class="wrap">
        <h1 class="text-3xl font-bold pb-6 pt-3 text-center">Create Person</h1>
        <form method="post" class="form" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="form_input rounded-tr-lg rounded-tl-lg">
            <input type="text" name="name" placeholder="Name" required="required">
          </div>

          <div class="border p-3 border-gray-400 flex justify-between">
            <input type="text" name="caption" class="p-1 w-full" placeholder="Caption">
            <input type="file" name="photo" class="p-1 w-full">
          </div>

          <div class="select rounded-br-lg rounded-bl-lg">
            <label for="kind">Kind</label>
            <select name="kind" id="kind" required="required">
              {% for akind in form.kind %}
                {{akind}}
              {% endfor %}
            </select>
          </div>

          <button class="form_button">Create</button>
        </form>
        <a href="{% url 'people:person-list' %}" class="block text-center w-full mt-3 px-1 py-2 bg-gray-500 text-white rounded-lg text-base font-bold tracking-wider outline-none border-none;">Back</a>
      </div>
    </div>
  </div>
{% endblock content %}

templates/pages/people/edit_person.html
{% extends 'base.html' %}

{% block page_title %}
  Edit Person
{% endblock page_title %}

{% block content %}
  <div class="background">
    <div class="wrap">
      <h1 class="text-3xl font-bold pb-6 pt-3 text-center">Edit Person</h1>
      <form method="post" class="form" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form_input rounded-tr-lg rounded-tl-lg">
          {{form.name}}
        </div>

        <div class="border p-3 border-gray-400 flex justify-between">
          <input type="text" name="caption" class="p-1 w-full" placeholder="Caption">
          <input type="file" name="photo" class="p-1 w-full">
        </div>

        <div class="select rounded-br-lg rounded-bl-lg">
          <label for="kind">Kink</label>
          {{form.kind}}
        </div>

        <button class="form_button">Edit</button>
      </form>
      <a href="{% url 'people:person-detail' person.pk %}" class="block text-center w-full mt-3 px-1 py-2 bg-gray-500 text-white rounded-lg text-base font-bold tracking-wider outline-none border-none;">Back</a>
    </div>
  </div>
{% endblock content %}

templates/pages/people/people_list.html
{% extends 'base.html' %}
{% comment %}  {% endcomment %}
{% block page_title %}
  People List
{% endblock page_title %}

{% block content %}
  <div class="mt-40 flex flex-col items-center justify-items-center h-screen">
    <div class="w-11/12 h-full">
      <div class="flex flex-col">
        <section class="home_section">
          <div class="flex justify-between items-center mb-4">
            <h4 class="text-2xl font-bold ">Latest People</h4>
            {% comment %} <a href="{% url 'people:people-create' %}" class="font-bold px-4 py-2 border-none rounded-lg bg-green-500 text-white">Create Movie</a> {% endcomment %}
          </div>
          <div class="section_grid">
            {% for person in people %}
              <a class="relative group" href="#">
                <img class="cover_image" src="{{person.photo.url|default_if_none:" "}}" alt="Cover Image">
                <div class="font-bold">
                  {{person.name}}
                </div>
                <div class="">
                  {{person.kind}}
                </div>
              </a>
            {% endfor %}
          </div>
        </section>
        <div class="flex justify-center mb-20">
          {% if page_obj.has_previous %}
            {% if page_sector|add:-4 <= 1 %}
              <a href="?page=1" class="mr-3 text-lg font-semibold">Prev</a>
            {% else %}
              <a href="?page={{page_sector|add:-4}}" class="mr-3 text-lg font-semibold">Prev</a>
            {% endif %}
          {% endif %}
          {% for number in '12345'|make_list %}
            {% if page_sector|add:number <= page_obj.paginator.num_pages %}
              <a href="?page={{page_sector|add:number}}" class="mr-2 py-1 px-2 text-lg rounded {% if page_sector|add:number == page_obj.number %} bg-green-400 text-white {% else %}text-gray-700 bg-gray-200{% endif %} hover:bg-green-200 hover:text-white">{{page_sector|add:number}}</a>
            {% endif %}
          {% endfor %}
          {% if page_obj.has_next %}
            {% if page_sector|add:6 >= page_obj.paginator.num_pages %}
              <a href="?page={{page_obj.paginator.num_pages}}" class="ml-1 text-lg font-semibold">Next</a>
            {% else %}
              <a href="?page={{page_sector|add:6}}" class="ml-1 text-lg font-semibold">Next</a>
            {% endif %}
          {% endif %}
        </div>
      </div>
    </div>
  </div>
{% endblock content%}


templates/pages/people/person_detail.html
{% extends 'base.html' %}

{% block page_title %}
  {{person.name}}
{% endblock page_title %}

{% block content %}
  <div class="w-full mt-20 max-h-full min-h-screen" style="background: rgba(20,20,20,1);">
    <div class="absolute w-full bg-cover bg-no-repeat bg-center h-full opacity-30" style="background-image:url({{person.photo.url}})"></div>
    <div class="flex px-20 py-20 justify-between">
      <div class="flex w-3/4">
        <img class="mr-4 w-1/4 z-10" src="{{person.photo.url}}" alt="Movie Cover Image">
        <div class="z-10">
          <div>
            <span class="detail_field">Name :</span>
            <span class="detail_answer">{{person.name}}</span>
          </div>
          <div>
            <span class="detail_field">Kind :</span>
            <span class="detail_answer">{{person.kind}}</span>
          </div>
        </div>
      </div>
      <a class="edit_button" href="{% url 'people:person-edit' person.pk %}">Edit Movie</a>
    </div>
  </div>
{% endblock content%}

templates/pages/people/person_list.html
{% extends 'base.html' %}
{% comment %}  {% endcomment %}
{% block page_title %}
  People List
{% endblock page_title %}

{% block content %}
  <div class="mt-40 flex flex-col items-center justify-items-center min-h-screen">
    <div class="w-10/12 h-full">
      <div class="flex flex-col">
        <section class="home_section mt-10 p-8 rounded-lg">
          <div class="flex justify-between items-center mb-8">
              <h4 class="text-2xl font-bold ">Latest People</h4>
              <a href="{% url 'people:person-create' %}" class="font-bold px-4 py-2 border-none rounded-lg bg-green-500 text-white">Create Person</a>
            </div>
          <div class="section_grid">
            {% for person in people %}
              {% include 'mixins/person.html' with person=person %}
            {% endfor %}
          </div>
          <a href="{% url 'people:person-list' %}" class="listLink">
            Go to People List &rarr;
          </a>
        </section>
        {% include 'mixins/page_number.html' with page_sector=page_sector page_obj=page_obj%}
      </div>
    </div>
  </div>
{% endblock content%}
