config/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("books/", include("books.urls", namespace="books")),
    path("movies/", include("movies.urls", namespace="movies")),
    path("category/", include("categories.urls", namespace="category")),
    path("people/", include("people.urls", namespace="people")),
    path("users/", include("users.urls", namespace="users")),
    path("favs/", include("favs.urls", namespace="favs")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from core import views as core_views

app_name = "core"

urlpatterns = [
    path("", core_views.homeView, name="home"),
    path("search/", core_views.searchView, name="search"),
]

movies/urls.py
from django.urls import path
from movies import views as movie_views

app_name = "movies"

urlpatterns = [
    path("", movie_views.MovieListView.as_view(), name="movie-list"),
    path("<int:pk>/", movie_views.MovieDetailView.as_view(), name="movie-detail"),
    path("create/", movie_views.CreateMovieView.as_view(), name="movie-create"),
    path("<int:pk>/edit/", movie_views.EditMovieView.as_view(), name="movie-edit"),
]

movies/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db.models import Q
from django.shortcuts import reverse

from core import models as core_models


class Movie(core_models.TimeStampedModel):

    """Movie Model Definition"""

    title = models.CharField(max_length=20)
    year = models.IntegerField(validators=[MinValueValidator(0)])
    cover_image = models.ImageField(upload_to="movie_cover_images", blank=True)
    rating = models.FloatField(validators=[MinValueValidator(0), MaxValueValidator(5)])
    director = models.ForeignKey(
        "people.Person",
        related_name="moviesDirector",
        on_delete=models.SET_NULL,
        null=True,
        limit_choices_to={"kind": "director"},
    )
    categories = models.ManyToManyField(
        "categories.Category",
        related_name="movies",
        blank=True,
        limit_choices_to=Q(kind="both") | Q(kind="movie"),
    )
    casts = models.ManyToManyField(
        "people.Person",
        related_name="moviesCasts",
        blank=True,
        limit_choices_to={"kind": "actor"},
    )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("movies:movie-detail", kwargs={"pk": self.pk})

movies/forms.py
from django import forms
from movies.models import Movie


class CreateMovieForm(forms.ModelForm):

    """Create Movie Form Definition"""

    class Meta:
        model = Movie
        fields = (
            "title",
            "year",
            "rating",
            "cover_image",
            "director",
            "categories",
            "casts",
        )

    def save(self, *args, **kwargs):
        Movie = super().save(commit=False)
        return Movie

movies/views.py
from django.views.generic import ListView, DetailView, FormView, UpdateView
from django.shortcuts import redirect, reverse

from movies.models import Movie
from reviews.models import Review
from movies.forms import CreateMovieForm


class MovieListView(ListView):

    """Movie List View"""

    model = Movie
    template_name = "pages/movies/movie_list.html"
    context_object_name = "movies"
    paginate_by = 10
    paginate_orphans = 6
    ordering = "created"

    def get_context_data(self):
        page = int(self.request.GET.get("page", 1))
        page_sector = (page - 1) // 5
        page_sector = page_sector * 5
        context = super().get_context_data()
        context["page_sector"] = page_sector
        return context


class MovieDetailView(DetailView):

    """Movie Detail View"""

    model = Movie
    template_name = "pages/movies/movie_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        movie = context["movie"]
        reviews = Review.objects.filter(movie=movie)
        context["reviews"] = reviews
        return context


class CreateMovieView(FormView):

    """Create Movie View Definition"""

    form_class = CreateMovieForm
    template_name = "pages/movies/create_movie.html"

    def form_valid(self, form):
        movie = form.save()
        movie.save()
        form.save_m2m()
        return redirect(reverse("movies:movie-detail", kwargs={"pk": movie.pk}))


class EditMovieView(UpdateView):

    """Edit Movie View Definition"""

    model = Movie
    template_name = "pages/movies/edit_movie.html"
    fields = (
        "title",
        "year",
        "rating",
        "director",
        "categories",
        "casts",
    )

    def get_form(self, form_class=None):
        form = super().get_form(form_class=form_class)
        form.fields["title"].widget.attrs = {"class": "w-full", "placeholder": "Title"}
        form.fields["year"].widget.attrs = {"class": "w-full", "placeholder": "Year"}
        form.fields["rating"].widget.attrs = {
            "class": "w-full",
            "placeholder": "Rating",
        }
        return form

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        return context

templates/pages/movies/create_movie.html
{% extends 'base.html' %}

{% block page_title %}
  Create Movie
{% endblock page_title %}

{% block content %}
  <div class="py-20">
    <div class="background">
      <div class="wrap">
        <h1 class="text-3xl font-bold pb-6 pt-3 text-center">Create Movie</h1>
        <form method="post" class="form" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="form_input rounded-tr-lg rounded-tl-lg">
            <input type="text" name="title" placeholder="Title" required="required">
          </div>

          <div class="number_input">
            <input type="number" name="year" class="w-full" min="0" placeholder="Year" required="required">
          </div>

          <div class="number_input">
            <input type="number" name="rating" class="w-full" min="0" max="5" placeholder="Rating" required="required">
          </div>

          <div class="border p-3 border-gray-400 flex justify-between">
            <input type="text" name="caption" class="p-1 w-full" placeholder="Caption">
            <input type="file" name="cover_image" class="p-1 w-full">
          </div>

          <div class="select">
            <label for="director">Director</label>
            <select name="director" id="director" required="required">
              {% for aDirector in form.director %}
                {{aDirector}}
              {% endfor %}
            </select>
          </div>

          <div class="checkbox">
            <h3>Categories</h3>

            <ul>
              {% for category in form.categories %}
                <li>
                  <label for="category_{{category.data.value}}">{{category.data.label}}</label>
                  <input type="checkbox" name="categories" value="{{category.data.value}}" id="category_{{category.data.value}}">
                </li>
              {% endfor %}
            </ul>
          </div>

          <div class="checkbox rounded-br-lg rounded-bl-lg">
            <h3>Casts</h3>

            <ul>
              {% for cast in form.casts %}
                <li>
                  <label for="cast_{{cast.data.value}}">{{cast.data.label}}</label>
                  <input type="checkbox" name="casts" value="{{cast.data.value}}" id="cast_{{cast.data.value}}">
                </li>
              {% endfor %}
            </ul>
          </div>

          <button class="form_button">Create</button>
        </form>
        <a href="{% url 'movies:movie-list' %}" class="back_button">Back</a>
      </div>
    </div>
  </div>
{% endblock content %}

templates/pages/movies/edit_movie.html
{% extends 'base.html' %}

{% block page_title %}
  Edit Movie
{% endblock page_title %}

{% block content %}
  <div class="background">
    <div class="wrap">
      <h1 class="text-3xl font-bold pb-6 pt-3 text-center">Edit Movie</h1>
      <form method="post" class="form" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form_input rounded-tr-lg rounded-tl-lg">
          {{form.title}}
        </div>

        <div class="number_input">
          {{form.year}}
        </div>

        <div class="number_input">
          {{form.rating}}
        </div>

        <div class="border p-3 border-gray-400 flex justify-between">
          <input type="text" name="caption" class="p-1 w-full" placeholder="Caption">
          <input type="file" name="cover_image" class="p-1 w-full">
        </div>

        <div class="checkbox">
          <h3>Category</h3>
          <ul>
            {% for category in form.categories %}
              <li>
                <label for="category_{{category.data.value}}">{{category.data.label}}</label>
                <input type="checkbox" name="categories" value="{{category.data.value}}" id="category_{{category.data.value}}" {% if category.data.selected %} checked="checked" {% endif %}>
              </li>
            {% endfor %}
          </ul>
        </div>

        <div class="checkbox">
          <h3>Casts</h3>
          <ul>
            {% for cast in form.casts %}
              <li>
                <label for="cast_{{cast.data.value}}">{{cast.data.label}}</label>
                <input type="checkbox" name="casts" value="{{cast.data.value}}" id="cast_{{category.data.value}}" {% if cast.data.selected %} checked="checked" {% endif %}>
              </li>
            {% endfor %}
          </ul>
        </div>

        <div class="select rounded-br-lg rounded-bl-lg">
          <label for="director">Director</label>
          {{form.director}}
        </div>

        <button class="form_button">Edit</button>
      </form>
      <a href="{% url 'movies:movie-detail' movie.pk %}" class="block text-center w-full mt-3 px-1 py-2 bg-gray-500 text-white rounded-lg text-base font-bold tracking-wider outline-none border-none;">Back</a>
    </div>
  </div>
{% endblock content %}

templates/pages/movies/movie_detail.html
{% extends 'base.html' %}

{% block page_title %}
  {{movie.title}}
{% endblock page_title %}

{% block content %}
  <div class="w-full mt-20 max-h-full min-h-screen" style="background: rgba(20,20,20,1);">
    <div class="absolute w-full bg-cover bg-no-repeat bg-center h-full opacity-30" style="background-image:url({{movie.cover_image.url}})"></div>
    <div class="flex px-20 py-20 justify-between">
      <div class="flex w-3/4">
        <img class="mr-4 w-1/4 z-10" src="{{movie.cover_image.url}}" alt="Movie Cover Image">
        <div class="z-10">
          <div>
            <span class="detail_field">Title :</span>
            <span class="detail_answer">{{movie.title}}</span>
          </div>
          <div>
            <span class="detail_field">Releasing Date :</span>
            <span class="detail_answer">{{movie.year}}</span>
          </div>
          <div>
            <span class="detail_field">Rating :</span>
            <span class="detail_answer">{{movie.rating}}
              / 5.0</span>
          </div>
          <div>
            <span class="detail_field">Director :</span>
            <span class="detail_answer">{{movie.director}}</span>
          </div>
          <div>
            <span class="detail_field">Categories :
            </span>
            {% for category in movie.categories.all %}
              {% if forloop.last %}
                <span class="detail_answer">{{category}}</span>
              {% else %}
                <span class="detail_answer">{{category}},
                </span>
              {% endif %}
            {% endfor %}
          </div>
          <div>
            <span class="detail_field">Casts :
            </span>
            {% for cast in movie.casts.all %}
              {% if forloop.last %}
                <span class="detail_answer">{{cast}}</span>
              {% else %}
                <span class="detail_answer">{{cast}},
                </span>
              {% endif %}
            {% endfor %}
          </div>
        </div>
      </div>
      <a class="edit_button" href="{% url 'movies:movie-edit' movie.pk %}">Edit Movie</a>
    </div>
  </div>
  {% comment %}  {% endcomment %}
  {% include 'mixins/reviews.html' with reviews=reviews type="movie" id=movie.pk %}
{% endblock content%}

templates/pages/movies/movie_list.html
{% extends 'base.html' %}
{% comment %}  {% endcomment %}
{% block page_title %}
  Movie List
{% endblock page_title %}

{% block content %}
  <div class="mt-40 flex flex-col items-center justify-items-center min-h-screen">
    <div class="w-10/12 h-full">
      <div class="flex flex-col">
        <section class="home_section mt-10 p-8 rounded-lg">
        <div class="flex justify-between items-center mb-8">
            <h4 class="text-2xl font-bold ">Latest Movies</h4>
            <a href="{% url 'movies:movie-create' %}" class="font-bold px-4 py-2 border-none rounded-lg bg-green-500 text-white">Create Movie</a>
          </div>
        <div class="section_grid">
          {% for movie in movies %}
            {% include 'mixins/movie.html' with movie=movie %}
          {% endfor %}
        </div>
        <a href="{% url 'movies:movie-list' %}" class="listLink">
          Go to Movie List &rarr;
        </a>
      </section>
        {% include 'mixins/page_number.html' with page_sector=page_sector page_obj=page_obj%}
      </div>
    </div>
  </div>
{% endblock content%}